name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  haxelib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.7
      - name: Package Haxelib
        working-directory: haxelib
        run: haxe haxelib.hxml
      - uses: actions/upload-artifact@v4
        with:
          name: feathersui-flex-migration-haxelib
          path: bin/haxelib/
          if-no-files-found: error

  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.7
      - uses: joshtynjala/setup-apache-flex-action@v2
        with:
          air-version: 33.1
          accept-air-license: true
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install feathersui --quiet
          haxelib install dox --quiet
          haxelib dev feathersui-flex-migration ${{ github.workspace }}
      - name: Build API reference
        working-directory: docs
        run: haxe docs.hxml
      - uses: actions/upload-artifact@v4
        with:
          name: feathersui-flex-migration-docs
          path: bin/api/
          if-no-files-found: error
      # - name: Deploy to unstable
      #   if: ${{ github.event_name != 'pull_request' }}
      #   uses: garygrossgarten/github-action-scp@release
      #   with:
      #     local: bin/api
      #     remote: api.feathersui.com/flex-migration/unstable
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     password: ${{ secrets.SSH_PASS }}

  flash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.7
      - uses: joshtynjala/setup-apache-flex-action@v2
        with:
          air-version: 33.1
          accept-air-license: true
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install feathersui --quiet
          haxelib dev feathersui-flex-migration ${{ github.workspace }}
      - name: Build Flash .swc library
        run: haxelib run lime build flash -debug
